project_name: Mobile_Automation
execution:
 mode: local #local/cloud
 platform: android #android/ios
 parallel: no #yes/no
 max_threads: 5
 retry: true #true/false
 
timeouts: #seconds
 implicit: 30 
 explicit: 30
 
 
platform_config:
 android:
   automation_name: UiAutomator2
   platform_version: "13"
   device_name: Pixel_7
   app_path: src/test/resources/app-debug.apk
 ios:
  automation_name: XCUITest
  platform_version: "17.0"
  device_name: iPhone 14
  app_path: src/test/resources/app.ipa
  
server:
 local:
  host: 127.0.0.1
  port: 4723
  start_server: true
  log_level: info
 cloud:
  url: https://hub.browserstack.com/wd/hub
  
cloud:
 browserstack:
  username: ${BS_USERNAME}
  access_key: ${BS_ACCESS_KEY}
  app_id_android: bs://abcdef123456
  app_id_ios: bs://xyz987654
  device_pool:
    - Pixel 8
    - Samsung Galaxy S23
    - iPhone 15
  os_versions:
   android:
    - "12"
    - "13"
   ios:
    - "16"
    - "17"
 
